name: Build Windows EXE (cx_Freeze)

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      PYTHON_VERSION: "3.10"
      ENTRY_SCRIPT: "umahelper.py"   # change if your main file is different
      APP_NAME: "UmaHelper"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Python info
        shell: pwsh
        run: |
          python -V
          pip -V

      - name: Install build tooling
        shell: pwsh
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install cx-Freeze==7.2.5

      # Prefer explicit installs (clean + deterministic). If you have a requirements.txt,
      # you can swap this step to `pip install -r requirements.txt` after updating it.
      - name: Install project dependencies
        shell: pwsh
        run: |
          pip install `
            numpy==1.26.4 `
            opencv-python-headless==4.6.0.66 `
            paddlepaddle==2.6.1 `
            paddleocr==2.7.3 `
            Pillow==10.3.0 `
            rapidfuzz==3.6.1 `
            PySide6==6.5.3 `
            mss==9.0.1

      # Optional: if you committed the downloader and want offline-first builds,
      # uncomment to prefetch models into ./paddle_models (bundled by your setup)
      # - name: Pre-download PaddleOCR models (optional)
      #   shell: pwsh
      #   run: |
      #     python - << 'PY'
      #     import os
      #     from pathlib import Path
      #     os.environ["PADDLEOCR_HOME"] = str((Path(".")/"paddle_models").resolve())
      #     from paddleocr import PaddleOCR
      #     PaddleOCR(lang="en", use_gpu=False)
      #     print("Models saved to:", os.environ["PADDLEOCR_HOME"])
      #     PY

      - name: Clean previous build
        shell: pwsh
        run: |
          python -c "import shutil; shutil.rmtree('build', ignore_errors=True)"


      - name: Build with cx_Freeze
        shell: pwsh
        env:
          ENTRY_SCRIPT: ${{ env.ENTRY_SCRIPT }}   # setup_cxfreeze.py reads this
        run: |
          python setup_cxfreeze.py build

      - name: Show build output
        shell: pwsh
        run: |
          Get-ChildItem -Recurse build | Select-Object FullName

      - name: Upload EXE and build folder
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-win-cxfreeze
          path: |
            build\exe*\${{ env.APP_NAME }}.exe
            build\exe*\
          if-no-files-found: error
