name: Build EXE (cx_Freeze)

on:
  push:
  pull_request:

jobs:
  windows-build:
    runs-on: windows-latest

    env:
      PYTHON_VERSION: "3.10"
      APP_NAME: "UmaHelper"
      ENTRY_SCRIPT: "main.py"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Show Python info
        run: |
          python -V
          pip -V

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools

      - name: Install project dependencies
        run: |
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          } else {
            pip install `
              numpy==1.26.4 `
              opencv-python==4.6.0.66 `
              paddlepaddle==2.6.1 `
              paddleocr==2.7.3 `
              Pillow==10.3.0 `
              rapidfuzz==3.6.1 `
              PySide6==6.5.3 `
              mss==9.0.1
          }

      - name: Install cx_Freeze
        run: |
          pip install cx-Freeze==7.2.5

      - name: Ensure setup script points to entry script
        shell: bash
        run: |
          sed -E -i 's/ENTRY_SCRIPT[[:space:]]*=[[:space:]]*".*"/ENTRY_SCRIPT = "'"$ENTRY_SCRIPT"'"/' setup_cxfreeze.py


      - name: Build with cx_Freeze
        run: |
          python setup_cxfreeze.py build
        shell: pwsh

      - name: Show build output
        run: |
          Get-ChildItem -Recurse build | Select-Object FullName

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-windows-cxfreeze
          path: |
            build\exe*\${{ env.APP_NAME }}.exe
          if-no-files-found: error
