name: Build UmaHelper (cx_Freeze)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install cx_Freeze
          pip install paddlepaddle==2.5.2
          pip install paddleocr
          pip install PySide6 rapidfuzz opencv-python-headless

      - name: Sanity check imports
        shell: pwsh
        run: |
          @'
          import sys
          try:
              import paddle
              print("OK: import paddle ->", getattr(paddle, "__version__", "unknown"))
              import paddleocr
              print("OK: import paddleocr")
          except Exception as e:
              print("Import failed:", e); sys.exit(1)
          '@ | python -

      - name: Clean previous build
        shell: pwsh
        run: |
          python -c "import shutil; shutil.rmtree('build', ignore_errors=True)"

      - name: Build with cx_Freeze
        run: python setup_cxfreeze.py build

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: UmaHelper_exe
          path: build/exe.win-amd64-3.10
