name: Build UmaHelper EXE

on:
  push:
    branches: [ "main" ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller mss pillow pytesseract rapidfuzz PySide6 numpy opencv-python pywin32

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller main.py `
            --name UmaHelper `
            --onefile `
            --noconsole `
            --add-data "assets;assets" `
            --add-data "roi;roi"

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: UmaHelper-Windows
          path: dist/UmaHelper.exe

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/UmaHelper.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
